---
- name: Configure Cisco Routers
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Configure MOTD Banner
      cisco.ios.ios_banner:
        banner: motd
        text: |
          ---------------------------------------
          WARNING: Authorized Access Only for G3nIu5
          Managed by Ansible & Jenkins with GitHub
          Automation with Webhook + ngrock & GNS3 + Cisco
          Tested by 19th Feb 2026 ver2 + added IOU_R
          ---------------------------------------
        state: present
