---
- name: Configure R1
  hosts: R1
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Configure MOTD Banner
      cisco.ios.ios_banner:
        banner: motd
        text: |
          ---------------------------------------
          WARNING: Authorized Access Only for G3nIu5
          Managed by Ansible & Jenkins with GitHub
          Automation with Webhook + ngrok & GNS3 + Cisco
          Tested by 19th Feb 2026 ver2 + added IOU_R
          ---------------------------------------

    - name: Configure Loopback100
      cisco.ios.ios_config:
        parents: interface Loopback100
        lines:
          - description Configured by Ansible ---
          - ip address 192.168.200.1 255.255.255.255
          - no shutdown

    - name: Configure Loopback101
      cisco.ios.ios_config:
        parents: interface Loopback101
        lines:
          - description Configured by Ansible ---
          - ip address 192.168.201.1 255.255.255.255
          - no shutdown

    - name: Configure Loopback102
      cisco.ios.ios_config:
        parents: interface Loopback102
        lines:
          - description Configured by Ansible ---
          - ip address 192.168.202.1 255.255.255.255
          - no shutdown

    - name: Configure Ethernet0/1 towards R2
      cisco.ios.ios_config:
        parents: interface Ethernet0/1
        lines:
          - description Link to R2
          - ip address 12.12.12.1 255.255.255.240
          - ip ospf 1 area 0
          - no shutdown

    - name: Configure OSPF process on R1
      cisco.ios.ios_config:
        parents: router ospf 1
        lines:
          - router-id 1.1.1.1
          - redistribute connected subnets
